#!/bin/bash -e

state="$1"

while read old new ref; do
	if [[ "$ref" =~ ^refs/([^/]*)/(.*)$ ]]; then
		type=${BASH_REMATCH[1]}
		id=${BASH_REMATCH[2]}

		if [[ $new =~ ^0+$ ]]; then
			action=del
		else
			action=new
		fi

		script="$0-$state-$action-$type"

		if [ -x $script ]; then
			$script $id $old $new
		fi
	fi
done

