services:
  dpsrv-bind:
    container_name: dpsrv-bind-${tag:-latest}
    image: dpsrv/bind:${tag:-latest}
    build: .
    hostname: $HOSTNAME.dpsrv.me
    ports:
      - "53/udp"
      - "53/tcp"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/bind/:/etc/bind/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
