services:
  nginx:
    container_name: bind
    image: dpsrv/bind
    build: .
    ports:
      - "50053:53/udp"
      - "50053:53/tcp"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/bind/:/etc/bind/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
